Fix actions endpoint for block dropdowns
slack-ruby/slack-ruby-bot-server-events pull request #10
Opened 2021-03-15 18:22 UTC by maths22

Make it so you can use this library for interactive dropdowns.  Those callbacks don't have a response url, so make it optional.

2021-03-16 16:27 UTC, dblock commented
Thanks, care to put this in CHANGELOG please, and maybe write a quick test with an actual payload?

2021-09-21 21:20 UTC, dblock requested changes
Still needs tests.

2021-09-21 21:20 UTC, dblock commented on CHANGELOG.md
Put back this line.

2022-02-28 16:10 UTC, dblock commented
Want to finish this @maths22 ?

2022-02-28 16:50 UTC, maths22 commented
Whoops, I forgot about this; will add tests

2022-02-28 17:20 UTC, maths22 commented
@dblock done and confirmed it passes locally; travis doesn't seem to be running to validate it there

2022-02-28 23:08 UTC, dblock commented
It's cause this:

<img width="1427" alt="Screen Shot 2022-02-28 at 6 07 38 PM" src="https://user-images.githubusercontent.com/542335/156073431-278f6e9f-4df1-4318-8638-ebcf0b8c8ac2.png">

We'll have to migrate this project to GHA, maybe someone (you?) could take care of it.

2022-03-21 08:16 UTC, CrazyOptimist commented
@maths22 you can merge `master` into your branch then CI will pass.

2022-03-21 15:00 UTC, maths22 commented
Ok it should be ready to run tests once you approve running them

2022-03-21 15:56 UTC, CrazyOptimist commented
@dblock `danger` is failing with this message:
```
Missing ENV['DATABASE_ADAPTER'].
Could not find the type of CI for Danger to run on.
```
Have you experienced the same? Please gimme some hint if yes.  
I will investigate it and commit on the next PR(mongo v5 one).

2022-03-21 16:35 UTC, merged

2022-03-21 16:36 UTC, dblock commented
I merged this, care to PR an update to that dangerfile @CrazyOptimist and let's see if that happens with the change?

2022-03-21 16:36 UTC, CrazyOptimist commented
Roger!